### ISSUE TITLE
Πρόβλημα με τις πληρωμές με πιστωτικές κάρτες (vivawallet)

### ISSUE THREAD

**Issue by gorakis** [somewherewarm/woocommerce-gateway-viva#11]
Γειά σας, 

Έχω ένα eshop το οποίο είναι στημένο σε wordpress και τρέχει woocomerce. Για να δέχομαι πληρωμές με πιστωτικές κάρτες έχω επιλεξει την vivawallet  και για την σύνδεση του woocomerce με την υπηρεσία(viva) χρησιμοποίησα το recommended plugin από το github, WooCommerce Viva Wallet Gateway Έκδοση 1.0.0 | Από SomewhereWarm. 

Έχω σετάρει και το plugin αλλά και τον λογαριασμό μου στην viva με βάση τις οδηγίες του plugin. Επίσης έχω δημιουργήσει μέσα από το dashboard της viva και ένα web hook ώστε μετά από μια πετυχημένη συναλλαγή να επιστρέφει στο site μου και να αλλάζει το status της παραγγελίας από "pending" σε "in proccess". Μέχρι εδώ όλα πηγαιναν τέλεια. 

Πρόσφατα παρατήρησα ότι κάποιες φορές (όχι πάντα) μετά από μία πετυχημένη συναλλαγή  γίνονται 2 request με αποτέλεσμα να αφαιρείται το stock των προϊόντων της παραγγελίας 2 φορές και να έρχονται σε εμένα αλλά και στον πελάτη 2 email επιβεβαίωσης (δεν δημιουργεί 2 παραγγελίες ούτε χρεωνει την κάρτα 2 φορές). 

Όλα τα Plugin αλλά και το wordpress ειναι updated. 

**Εμπειρικά διαπίστωσα (πρίν φτιάξω το webhook) ότι άν κάνεις την διαδικασία της ενημέρωσης του status της παραγγελίας χειροκίνητα και ενώ έχεις πατήσει update και φορτώνει κάνεις κλίκ ξανά στο κουμπί "update" στέλνει 2 email επιβεβαίωσης. 

Μπορείτε να με βοηθήσετε να λύσω αυτό το πρόβλημα ή να με βοηθήσετε από που προέρχεται?? 

Έχω απευθυνθεί και στο vivawallet αλλά και στο στην υπηρεσία hosting και αναμένω κάποια απάντηση.

Ευχαριστώ

**Comment by franticpsyx** [comment]
Καλησπέρα @gorakis 

Thanks για το issue report.

Θα μπορούσες να κατεβάσεις και να δοκιμάσεις την έκδοση 1.0.1 από εδώ -- https://cl.ly/c54784c0ce04 ?

Λογικά θα διορθώσει το πρόβλημα. Παρακαλώ στείλε μας ένα update για επιβεβαίωση! Thanks!

**Comment by gorakis** [comment]
Καλημέρα σας, εγκατέστησα την νέα έκδοση και δέιχνει να λειτουεγςλι φυσιολογικά. θα το ελέγξω και τις επόμενες μέρες και αν χρειαστεί θα επικοινωνήσω μαζί σας.

Σας ευχαριστώ πολύ για την άμεση απάντηση.

Καλή συνέχεια
